[versions]
agp = "9.2.0"
kotlin = "2.3.21"
kotlin-stdlib = "1.5.0"
dokka = "2.2.0"
lint = "32.2.0"
gradle-cmake = "1.2.2"
maven-publish = "0.36.0"
flatbuffers = "25.2.10"
junit4 = "4.13.2"
xposed = "82"
androidx-appcompat = "1.7.1"
material = "1.13.0"
ndk-cxx = "1.2.0"

[libraries]
flatbuffers-java = { module = "com.google.flatbuffers:flatbuffers-java", version.ref = "flatbuffers" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
ndk-cxx = { module = "dev.rikka.ndk.thirdparty:cxx", version.ref = "ndk-cxx" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
lint = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-cmake = { id = "io.github.tomtzook.gradle-cmake", version.ref = "gradle-cmake" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
